version: "2"
services:
  web:
    image: myapp
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  mongodb:
    image: mvertes/alpine-mongo
    network_mode: host
    restart: always
    volumes:
      - $HOME/mongo/data:/data/db
    expose:
      - 27017
    ports:
      - "27017:27017"
